name: Prod Deployment

on:
  push:
    branches: ["master"]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    name: Building App
    strategy:
      matrix:
        node-version: [12.]

    steps:
    - name: Setup Node.js
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci

    - name: Build
    - run: npm run build --if-present

  deploy_prod:
    name: Production
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checking out Repository
        uses: actions/checkout@master

      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: backend-release
          path: build
        
      - name: Deploying to Production Server Via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_HOST_PROD }}
          username: ${{ secrets.FTP_USER_PROD }}
          password: ${{ secrets.FTP_PASS_PROD }}
          server-dir: ${{ secrets.FTP_PATH_PROD }}
          local-dir: ./build/
